import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Iframe from 'react-iframe'
import logo from '../public/logo.jpg'


const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>The GemsTones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="title">
          <Image 
            src={logo}
            alt="The GemsTones Logo"
            width="100px"
            height="100px"
          />
          <h1>The GemsTones</h1>
        </div>
        <nav>
          <a href="">Home</a>
          <a href="">About</a>
          <a href="">Gallery</a>
          <a href="">Calander</a>
          <a href="">Contact</a>
        </nav>
      </header>

      <main>
        <Iframe url="https://www.youtube.com/embed/MtN1YnoL46Q"
          className={styles.featured}
          width="100%"
          height="100%"
          position="relative"
        />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
