import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Iframe from 'react-iframe'
import logo from '../public/logo.jpg'


const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>The GemsTones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/syq1pzk.css" />
      </Head>

      <header>
        <div className="title">
          <Image 
            src={logo}
            alt="The GemsTones Logo"
            width="200px"
            height="200px"
          />
        </div>
        <nav>
          <a href="">Home</a>
          <a href="">About</a>
          <a href="">Gallery</a>
          <a href="">Calander</a>
          <a href="">Contact</a>
        </nav>
      </header>

      <main>
        <div className={styles.featuredContainer}>
          <Iframe 
            url="https://www.youtube.com/embed/_qQzuvfvBdE"
            className={styles.featured}
          />
        </div>
      </main>

      <footer>
        <p>demo text</p>
      </footer>
    </div>
  )
}

export default Home
